name: Code style black

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    name: black
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check
        uses: psf/black@stable
        with:
          options: "--check --verbose"
        continue-on-error: true
