name: Code style isort

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    name: isort
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Check
        uses: isort/isort-action@v1
        with:
          configuration: "--check-only"
